WebLabs_V2/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebLabs_V3.DAL.Interfaces;
using WebLabs_V3.DAL.Entities;

namespace WebLabs_V3.Controllers
{
    [Authorize(Roles ="admin")]
    public class AdminController : Controller
    {  
        IRepository<Dish> repository;
        public AdminController(IRepository<Dish> repo)
        {
            repository = repo;
        }
        // GET: Admin
        public ActionResult Index()
        {
            return View(repository.GetAll());
        }

       
        // GET: Admin/Create
        public ActionResult Create()
        {
            return View(new Dish());
        }

        // POST: Admin/Create
        [HttpPost]
        public ActionResult Create(Dish dish, HttpPostedFileBase imageUpload=null)
        {
            if (ModelState.IsValid)
            {
                if (imageUpload != null)
                {
                    var count = imageUpload.ContentLength;
                    dish.Image = new byte[count];
                    imageUpload.InputStream.Read(dish.Image, 0, (int)count);
                    dish.MimeType = imageUpload.ContentType;
                }
                try
                {
                    repository.Create(dish);
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }
            else return View(dish);
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int id)
        {
            return View(repository.Get(id));
        }

        // POST: Admin/Edit/5
        [HttpPost]
        public ActionResult Edit(Dish dish, HttpPostedFileBase imageUpload)
        {
            if (ModelState.IsValid)
            {
                if (imageUpload != null)
                {
                    var count = imageUpload.ContentLength;
                    dish.Image = new byte[count];
                    imageUpload.InputStream.Read(dish.Image, 0, (int)count);
                    dish.MimeType = imageUpload.ContentType;
                }
                try
                {
                    repository.Update(dish);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    return View(dish);
                }
            }
            else return View(dish);
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int id)
        {
            return View(repository.Get(id));
        }

        // POST: Admin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, bool result)
        {
            try
            {
                repository.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebLabs_V2/Controllers/DishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

using WebLabs_V3.DAL.Entities;
using WebLabs_V3.DAL.Interfaces;
using WebLabs_V3.Models;


namespace WebLabs_V3.Controllers
{    
    public class DishController : Controller
    {
        int pageSize = 3 ;
        // Инициализация списка объектов:
        //List<Dish> dishes = new List<Dish>
        //{
        //    new Dish {DishId=1, DishName="Суп-харчо", Description="Очень острый, невкусный",
        //            Calories =200, GroupName="Супы" },
        //        new Dish {DishId=2, DishName="Борщ", Description="Много сала, без сметаны",
        //            Calories =330, GroupName="Супы" },
        //        new Dish {DishId=3, DishName="Котлета пожарская", Description="Хлеб - 80%, Морковь - 20%",
        //            Calories =635, GroupName="Вторые блюда" },
        //        new Dish {DishId=4, DishName="Макароны по-флотски", Description="С охотничьей колбаской",
        //            Calories =524, GroupName="Вторые блюда" },
        //        new Dish {DishId=5, DishName="Компот", Description="Быстро растворимый, 2 литра",
        //            Calories =180, GroupName="Напитки" }
        //};

        IRepository<Dish> repository;

        public DishController(IRepository<Dish> repo)
        {
            repository = repo;
        }

        // GET: Dish       
        public ActionResult List(string group, int page=1)
        {
            var lst = repository.GetAll()
                        .Where(d=> group==null
                                    || d.GroupName.Equals(group))
                        .OrderBy(d => d.Calories);
            var model = PageListViewModel<Dish>.CreatePage(lst, page, pageSize);
            if (Request.IsAjaxRequest())
            {
                return PartialView("ListPartial", model);
            }
            return View(model);
        }

        public async Task<FileResult> GetImage(int id)
        {
            var dish = await repository.GetAsync(id);
            if (dish != null)
            {
                return new FileContentResult(dish.Image, dish.MimeType);
            }
            else return null;
        }
    }
}

WebLabs_V2/Views/Admin/Create.cshtml
@model WebLabs_V3.DAL.Entities.Dish

@{
    ViewBag.Title = "Добавить";
}

<h2>Добавить</h2>
@using (Html.BeginForm("Create",
                        "Admin", 
                        FormMethod.Post, 
                        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Новое блюдо</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DishName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DishName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DishName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Calories, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Calories, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Calories, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
            </div>
        </div>      
        <div class="form-group">
            @Html.Label("Выберите файл",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="imageUpload" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @if (Model.Image == null)
                {<p>Нет изображения</p>}
                else
                {<img width="150" height="150"
                      src="@Url.Action("GetImage", "Dish", new {Model.DishId})"
                      class="img-thumbnail"> }
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    }

WebLabs_V2/Views/Admin/Delete.cshtml
@model WebLabs_V3.DAL.Entities.Dish

@{
    ViewBag.Title = "Delete";
}

<h2>Удалить</h2>

<h3>Вы уверены?</h3>
<div>
    <h4>Dish</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DishName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DishName)
        </dd>     

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад к списку", "Index")
        </div>
    }
</div>

WebLabs_V2/Views/Admin/Edit.cshtml
@model WebLabs_V3.DAL.Entities.Dish

@{
    ViewBag.Title = "Редактирование";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Dish</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DishId)

        <div class="form-group">
            @Html.LabelFor(model => model.DishName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DishName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DishName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Calories, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Calories, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Calories, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Выберите файл", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="imageUpload" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @if (Model.Image == null)
                {<p>Нет изображения</p>}
                else
                {<img width="150" height="150" name="imageData"
                      src="@Url.Action("GetImage", "Dish", new {id=Model.DishId})"
                      class="img-thumbnail"> }
            </div>
        </div>
        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад, к списку", "Index")
</div>

WebLabs_V2/Views/Admin/Index.cshtml
@model IEnumerable<WebLabs_V3.DAL.Entities.Dish>

<p>
    @Html.ActionLink("Добавить", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DishName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Calories)
        </th>
        <th>
            @Html.DisplayNameFor(model=>model.GroupName)
        </th>
        <th></th>
       
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(@Html.DisplayFor(modelItem => item.DishName).ToString(),
                                            "Edit", 
                                            new { id = item.DishId })           
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Calories)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GroupName)
        </td>        
        <td>           
            @Html.ActionLink("Удалить", "Delete", new { id=item.DishId })
        </td>
    </tr>
}

</table>