WebLabs_V2/Controllers/DishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

using WebLabs_V3.DAL.Entities;
using WebLabs_V3.DAL.Interfaces;
using WebLabs_V3.Models;


namespace WebLabs_V3.Controllers
{    
    public class DishController : Controller
    {
        int pageSize = 3 ;
        // Инициализация списка объектов:
        //List<Dish> dishes = new List<Dish>
        //{
        //    new Dish {DishId=1, DishName="Суп-харчо", Description="Очень острый, невкусный",
        //            Calories =200, GroupName="Супы" },
        //        new Dish {DishId=2, DishName="Борщ", Description="Много сала, без сметаны",
        //            Calories =330, GroupName="Супы" },
        //        new Dish {DishId=3, DishName="Котлета пожарская", Description="Хлеб - 80%, Морковь - 20%",
        //            Calories =635, GroupName="Вторые блюда" },
        //        new Dish {DishId=4, DishName="Макароны по-флотски", Description="С охотничьей колбаской",
        //            Calories =524, GroupName="Вторые блюда" },
        //        new Dish {DishId=5, DishName="Компот", Description="Быстро растворимый, 2 литра",
        //            Calories =180, GroupName="Напитки" }
        //};

        IRepository<Dish> repository;

        public DishController(IRepository<Dish> repo)
        {
            repository = repo;
        }

        // GET: Dish       
        public ActionResult List(string group, int page=1)
        {
            var lst = repository.GetAll()
                        .Where(d=> group==null
                                    || d.GroupName.Equals(group))
                        .OrderBy(d => d.Calories);
            var model = PageListViewModel<Dish>.CreatePage(lst, page, pageSize);
            if (Request.IsAjaxRequest())
            {
                return PartialView("ListPartial", model);
            }
            return View(model);
        }

        public async Task<FileResult> GetImage(int id)
        {
            var dish = await repository.GetAsync(id);
            if (dish != null)
            {
                return new FileContentResult(dish.Image, dish.MimeType);
            }
            else return null;
        }
    }
}

WebLabs_V2/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebLabs_V3.Models;
using WebLabs_V3.DAL.Interfaces;
using WebLabs_V3.DAL.Entities;

namespace WebLabs_V3.Controllers
{
    public class MenuController : Controller
    {
        List<MenuItem> items;
        IRepository<Dish> repository;
          
        public MenuController(IRepository<Dish> repo)
        {
            repository = repo;
            items = new List<MenuItem>
            {
            new MenuItem{Name="Домой", Controller="Home", Action="Index", Active=string.Empty},
            new MenuItem{Name="Меню", Controller="Dish", Action="List", Active=string.Empty},
            new MenuItem{Name="Администрирование", Controller="Admin", Action="Index", Active=string.Empty},
            };
        }
        // GET: Menu
        public PartialViewResult Main(string c = "Home")
        {
            var current = items
                    .Where(i => string.Compare(i.Controller,c, true)==0)
                    .FirstOrDefault();
            if (current!=null)
            {
                current.Active="active";
            };
            return PartialView(items);
        }

        public PartialViewResult UserInfo()
        {
            return PartialView();
        }

        public PartialViewResult Side()
        {
            var groups = repository
                                .GetAll()
                                .Select(d => d.GroupName)
                                .Distinct();       
            return PartialView(groups);
        }

        public PartialViewResult Map()
        {
            return PartialView(items);
        }
    }
}

WebLabs_V2/Views/Dish/List.cshtml
@model WebLabs_V3.Models.PageListViewModel<WebLabs_V3.DAL.Entities.Dish>
@using System.Text;
@{
    ViewBag.Title = "List";
}

<h2>List</h2>
@*@{
    // объект для "собирания" разметки
    StringBuilder result = new StringBuilder();
    // счетчик эскизов в строке 
    var i = 0;
    TagBuilder row =new TagBuilder("div");

    foreach (var item in Model)
    {
        i++;
        if (i == 1) // для первого элемента в строке создаем новую строку
        {
            row = new TagBuilder("div");
            row.AddCssClass("row");
            row.AddCssClass("item-row");
        }
        row.InnerHtml += Html.Partial("ItemViewPartial", item);

        if (i == 3) // если строка закончена
        {
            // добавить строку в разметку
            result.Append(row.ToString());
            // обнулить счетчик элементов в строке
            i = 0;
        }
    }

    if (i != 0) // если последняя строка не заполнена
    {
        // добавить строку в разметку
        result.Append(row.ToString());
    }

}*@

<div id="List">
    <!-- Получить готовую разметку -->
    @*@MvcHtmlString.Create(result.ToString())
    @Html.Partial("PagerPartial", Model)*@

    @Html.Partial("ListPartial", Model);
</div>

@section SidePanel{
    @Html.Action("Side","Menu")
}

WebLabs_V2/Views/Dish/ListPartial.cshtml
@model WebLabs_V3.Models.PageListViewModel<WebLabs_V3.DAL.Entities.Dish>
@using System.Text;

@{
    // объект для "собирания" разметки
    StringBuilder result = new StringBuilder();
    // счетчик эскизов в строке
    var i = 0;
    TagBuilder row = new TagBuilder("div");

    foreach (var item in Model)
    {
        i++;
        if (i == 1) // для первого элемента в строке создаем новую строку
        {
            row = new TagBuilder("div");
            row.AddCssClass("row");
            row.AddCssClass("item-row");
        }
        row.InnerHtml += Html.Partial("ItemViewPartial", item);

        if (i == 3) // если строка закончена
        {
            // добавить строку в разметку
            result.Append(row.ToString());
            // обнулить счетчик элементов в строке
            i = 0;
        }
    }

    if (i != 0) // если последняя строка не заполнена
    {
        // добавить строку в разметку
        result.Append(row.ToString());
    }
}
    <!-- Получить готовую разметку -->
    @MvcHtmlString.Create(result.ToString())
    @Html.Partial("PagerPartial", Model)